// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {model} from '../models';

export function AddTask(arg1:string,arg2:string):Promise<string>;

export function BoardcastCtx(arg1:context.Context):Promise<void>;

export function ConvertTask(arg1:model.Item):Promise<string>;

export function ConvertTaskView(arg1:Array<model.TaskView>):Promise<model.Item>;

export function GetTasks(arg1:Array<string>):Promise<{[key: string]: Array<model.TaskView>}>;

export function Greet(arg1:string):Promise<string>;
