// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTask(arg1, arg2) {
  return window['go']['app']['App']['AddTask'](arg1, arg2);
}

export function BoardcastCtx(arg1) {
  return window['go']['app']['App']['BoardcastCtx'](arg1);
}

export function ConvertTaskView(arg1) {
  return window['go']['app']['App']['ConvertTaskView'](arg1);
}

export function GetTasks(arg1) {
  return window['go']['app']['App']['GetTasks'](arg1);
}

export function Greet(arg1) {
  return window['go']['app']['App']['Greet'](arg1);
}
